# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
