# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time_3',
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(default=b'', max_length=100, null=True),
        ),
    ]
