# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('match_id',),
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=b'', max_length=100)),
                ('first_name', models.CharField(default=b'', max_length=100)),
                ('last_name', models.CharField(default=b'', max_length=100)),
                ('pref_time', models.DateTimeField()),
                ('known_lang', models.CharField(choices=[(b'eng', b'English'), (b'chi', b'Mandarin'), (b'spa', b'Spanish')], default=b'', max_length=100)),
                ('learn_lang', models.CharField(choices=[(b'eng', b'English'), (b'chi', b'Mandarin'), (b'spa', b'Spanish')], default=b'', max_length=100)),
            ],
            options={
                'ordering': ('user_id',),
                'db_table': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='user_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator', to='demo.Profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='user_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to='demo.Profile'),
        ),
    ]
